language: go
sudo: false
go:
 - "1.17"
 - "1.16"
 - dev
 - master
 
script:
  - go test -v *.go -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)